apiVersion: batch/v1beta1
kind: CronJob
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    rerost.com/deploy-target: "true"
    rerost.com/deploy-target-container: web
    rerost.com/github: web=rerost/pubsub-duplicate-sample
  name: publisher
  labels:
    run: publisher
    name: publisher
    namespace: default
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: google-cloud-key
              secret:
                secretName: pubsub-key-publisher
          containers:
            - image: rerost/pubsub-proxy:latest
              imagePullPolicy: Always
              name: publisher
              command: ["/app/bin/publisher"]
              volumeMounts:
                - name: google-cloud-key
                  mountPath: /var/secrets/google
              env:
                - name: PUBSUB_TOPIC
                  value: test-duplicate
                - name: PUBSUB_SUB
                  value: test-duplicate-subscription
                - name: GOOGLE_CLOUD_PROJECT
                  value: k8s-test-219404
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: /var/secrets/google/pubsub-key-publisher.json
            - image: rerost/pubsub-proxy:latest
              imagePullPolicy: Always
              name: publisher
              command: ["/app/bin/server"]
              volumeMounts:
                - name: google-cloud-key
                  mountPath: /var/secrets/google
              env:
                - name: PUBSUB_TOPIC
                  value: test-duplicate
                - name: PUBSUB_SUB
                  value: test-duplicate-subscription
                - name: GOOGLE_CLOUD_PROJECT
                  value: k8s-test-219404
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: /var/secrets/google/pubsub-key-publisher.json
          restartPolicy: OnFailure
